// GENERATED by scripts/generate-label-icons.mjs from engine-web src/labels/icons.ts — do not edit.
// Label icons (HOLO_ICONS, POI_GLYPHS) as vector shapes, icon colours and default label subtitles.
#include "maprama/LabelIcons.hpp"

namespace maprama {

namespace {

const float holo_subway_c0[] = {8.0f, 2.8f, 12.0f, 2.8f, 13.6569f, 2.8f, 15.0f, 4.1431f, 15.0f, 5.8f, 15.0f, 11.4f, 15.0f, 13.0569f, 13.6569f, 14.4f, 12.0f, 14.4f, 8.0f, 14.4f, 6.3431f, 14.4f, 5.0f, 13.0569f, 5.0f, 11.4f, 5.0f, 5.8f, 5.0f, 4.1431f, 6.3431f, 2.8f, 8.0f, 2.8f};
const float holo_subway_c1[] = {7.9f, 4.8f, 12.1f, 4.8f, 12.5971f, 4.8f, 13.0f, 5.2029f, 13.0f, 5.7f, 13.0f, 6.5f, 13.0f, 6.9971f, 12.5971f, 7.4f, 12.1f, 7.4f, 7.9f, 7.4f, 7.4029f, 7.4f, 7.0f, 6.9971f, 7.0f, 6.5f, 7.0f, 5.7f, 7.0f, 5.2029f, 7.4029f, 4.8f, 7.9f, 4.8f};
const float holo_subway_c2[] = {5.0f, 9.4f, 15.0f, 9.4f};
const float holo_subway_c3[] = {8.4f, 11.8f, 8.4f, 12.1314f, 8.1314f, 12.4f, 7.8f, 12.4f, 7.4686f, 12.4f, 7.2f, 12.1314f, 7.2f, 11.8f, 7.2f, 11.4686f, 7.4686f, 11.2f, 7.8f, 11.2f, 8.1314f, 11.2f, 8.4f, 11.4686f, 8.4f, 11.8f};
const float holo_subway_c4[] = {12.8f, 11.8f, 12.8f, 12.1314f, 12.5314f, 12.4f, 12.2f, 12.4f, 11.8686f, 12.4f, 11.6f, 12.1314f, 11.6f, 11.8f, 11.6f, 11.4686f, 11.8686f, 11.2f, 12.2f, 11.2f, 12.5314f, 11.2f, 12.8f, 11.4686f, 12.8f, 11.8f};
const float holo_subway_c5[] = {7.2f, 17.4f, 8.6f, 14.4f, 12.8f, 17.4f, 11.4f, 14.4f};
const IconShape holo_subway_shapes[] = {
    {IconPaint::None, 1.0f, IconPaint::Current, 1.6f, "MLCLCLCLCZ", holo_subway_c0, 34},
    {IconPaint::Accent, 1.0f, IconPaint::None, 1.6f, "MLCLCLCLCZ", holo_subway_c1, 34},
    {IconPaint::None, 1.0f, IconPaint::Current, 1.6f, "ML", holo_subway_c2, 4},
    {IconPaint::Current, 1.0f, IconPaint::Current, 1.6f, "MCCCCZ", holo_subway_c3, 26},
    {IconPaint::Current, 1.0f, IconPaint::Current, 1.6f, "MCCCCZ", holo_subway_c4, 26},
    {IconPaint::None, 1.0f, IconPaint::Current, 1.6f, "MLML", holo_subway_c5, 8},
};
const IconDrawing holo_subway = {20.0f, true, holo_subway_shapes, 6, nullptr};

const float holo_cafe_c0[] = {4.0f, 8.8f, 13.0f, 8.8f, 13.0f, 12.6f, 13.0f, 14.5882f, 11.3882f, 16.2f, 9.4f, 16.2f, 7.6f, 16.2f, 5.6118f, 16.2f, 4.0f, 14.5882f, 4.0f, 12.6f};
const float holo_cafe_c1[] = {13.0f, 10.0f, 14.2f, 10.0f, 15.2493f, 10.0f, 16.1f, 10.8507f, 16.1f, 11.9f, 16.1f, 12.9493f, 15.2493f, 13.8f, 14.2f, 13.8f, 13.0f, 13.8f};
const float holo_cafe_c2[] = {7.0f, 3.2f, 6.1f, 4.2f, 7.9f, 5.1f, 7.0f, 6.3f, 10.0f, 3.2f, 9.1f, 4.2f, 10.9f, 5.1f, 10.0f, 6.3f};
const IconShape holo_cafe_shapes[] = {
    {IconPaint::Accent, 0.32f, IconPaint::Current, 1.6f, "MLLCLCZ", holo_cafe_c0, 20},
    {IconPaint::None, 1.0f, IconPaint::Current, 1.6f, "MLCCL", holo_cafe_c1, 18},
    {IconPaint::None, 1.0f, IconPaint::Current, 1.6f, "MCMC", holo_cafe_c2, 16},
};
const IconDrawing holo_cafe = {20.0f, true, holo_cafe_shapes, 3, nullptr};

const float holo_store_c0[] = {4.4f, 6.8f, 15.6f, 6.8f, 14.7f, 16.4f, 14.6476f, 17.0787f, 14.0807f, 17.602f, 13.4f, 17.6f, 6.6f, 17.6f, 5.9193f, 17.602f, 5.3524f, 17.0787f, 5.3f, 16.4f};
const float holo_store_c1[] = {7.4f, 9.0f, 7.4f, 5.9f, 7.4f, 4.4641f, 8.5641f, 3.3f, 10.0f, 3.3f, 11.4359f, 3.3f, 12.6f, 4.4641f, 12.6f, 5.9f, 12.6f, 9.0f};
const IconShape holo_store_shapes[] = {
    {IconPaint::Accent, 0.32f, IconPaint::Current, 1.6f, "MLLCLCZ", holo_store_c0, 20},
    {IconPaint::None, 1.0f, IconPaint::Current, 1.6f, "MLCCL", holo_store_c1, 18},
};
const IconDrawing holo_store = {20.0f, true, holo_store_shapes, 2, nullptr};

const float holo_music_c0[] = {14.6f, 11.0f, 14.6f, 14.3137f, 11.9137f, 17.0f, 8.6f, 17.0f, 5.2863f, 17.0f, 2.6f, 14.3137f, 2.6f, 11.0f, 2.6f, 7.6863f, 5.2863f, 5.0f, 8.6f, 5.0f, 11.9137f, 5.0f, 14.6f, 7.6863f, 14.6f, 11.0f};
const float holo_music_c1[] = {10.6f, 11.0f, 10.6f, 12.1046f, 9.7046f, 13.0f, 8.6f, 13.0f, 7.4954f, 13.0f, 6.6f, 12.1046f, 6.6f, 11.0f, 6.6f, 9.8954f, 7.4954f, 9.0f, 8.6f, 9.0f, 9.7046f, 9.0f, 10.6f, 9.8954f, 10.6f, 11.0f};
const float holo_music_c2[] = {14.6f, 2.8f, 14.6f, 9.2f, 14.6f, 2.8f, 16.1f, 3.1f, 17.1f, 4.1f, 17.3f, 5.5f};
const IconShape holo_music_shapes[] = {
    {IconPaint::None, 1.0f, IconPaint::Current, 1.6f, "MCCCCZ", holo_music_c0, 26},
    {IconPaint::Accent, 1.0f, IconPaint::None, 1.6f, "MCCCCZ", holo_music_c1, 26},
    {IconPaint::None, 1.0f, IconPaint::Current, 1.6f, "MLMC", holo_music_c2, 12},
};
const IconDrawing holo_music = {20.0f, true, holo_music_shapes, 3, nullptr};

const float holo_school_c0[] = {10.0f, 3.8f, 2.4f, 7.4f, 10.0f, 11.0f, 17.6f, 7.4f};
const float holo_school_c1[] = {5.4f, 9.1f, 5.4f, 12.8f, 6.6f, 14.1f, 8.2f, 14.8f, 10.0f, 14.8f, 11.8f, 14.8f, 13.4f, 14.1f, 14.6f, 12.8f, 14.6f, 9.1f, 17.6f, 7.4f, 17.6f, 11.6f};
const IconShape holo_school_shapes[] = {
    {IconPaint::Accent, 0.32f, IconPaint::Current, 1.6f, "MLLLZ", holo_school_c0, 8},
    {IconPaint::None, 1.0f, IconPaint::Current, 1.6f, "MLCCLML", holo_school_c1, 22},
};
const IconDrawing holo_school = {20.0f, true, holo_school_shapes, 2, nullptr};

const float holo_book_c0[] = {10.0f, 5.4f, 8.5f, 4.2f, 6.4f, 3.9f, 3.4f, 4.1f, 3.4f, 14.9f, 6.4f, 14.7f, 8.5f, 15.0f, 10.0f, 16.2f, 11.5f, 15.0f, 13.6f, 14.7f, 16.6f, 14.9f, 16.6f, 4.1f, 13.6f, 3.9f, 11.5f, 4.2f, 10.0f, 5.4f};
const float holo_book_c1[] = {10.0f, 5.4f, 10.0f, 16.2f};
const float holo_book_c2[] = {5.6f, 7.3f, 6.7f, 7.3f, 7.6f, 7.5f, 8.4f, 7.9f, 11.6f, 7.9f, 12.4f, 7.5f, 13.3f, 7.3f, 14.4f, 7.3f};
const IconShape holo_book_shapes[] = {
    {IconPaint::None, 1.0f, IconPaint::Current, 1.6f, "MCLCCLCZ", holo_book_c0, 30},
    {IconPaint::None, 1.0f, IconPaint::Current, 1.6f, "ML", holo_book_c1, 4},
    {IconPaint::None, 1.0f, IconPaint::Accent, 1.6f, "MCMC", holo_book_c2, 16},
};
const IconDrawing holo_book = {20.0f, true, holo_book_shapes, 3, nullptr};

const float holo_plaza_c0[] = {17.0f, 10.0f, 17.0f, 13.866f, 13.866f, 17.0f, 10.0f, 17.0f, 6.134f, 17.0f, 3.0f, 13.866f, 3.0f, 10.0f, 3.0f, 6.134f, 6.134f, 3.0f, 10.0f, 3.0f, 13.866f, 3.0f, 17.0f, 6.134f, 17.0f, 10.0f};
const float holo_plaza_c1[] = {10.0f, 5.9f, 11.2f, 8.3f, 13.9f, 8.7f, 11.9f, 10.6f, 12.4f, 13.2f, 10.0f, 12.0f, 7.6f, 13.2f, 8.1f, 10.6f, 6.1f, 8.7f, 8.8f, 8.3f};
const IconShape holo_plaza_shapes[] = {
    {IconPaint::None, 1.0f, IconPaint::Current, 1.6f, "MCCCCZ", holo_plaza_c0, 26},
    {IconPaint::Accent, 1.0f, IconPaint::None, 1.6f, "MLLLLLLLLLZ", holo_plaza_c1, 20},
};
const IconDrawing holo_plaza = {20.0f, true, holo_plaza_shapes, 2, nullptr};

const float holo_park_c0[] = {10.0f, 3.2f, 11.3713f, 3.1996f, 12.6606f, 3.8533f, 13.4707f, 4.9598f, 14.2808f, 6.0663f, 14.5146f, 7.4928f, 14.1f, 8.8f, 15.4324f, 9.4897f, 16.1553f, 10.9713f, 15.8788f, 12.446f, 15.6022f, 13.9207f, 14.3918f, 15.0398f, 12.9f, 15.2f, 7.1f, 15.2f, 5.6082f, 15.0398f, 4.3978f, 13.9207f, 4.1212f, 12.446f, 3.8447f, 10.9713f, 4.5676f, 9.4897f, 5.9f, 8.8f, 5.4854f, 7.4928f, 5.7192f, 6.0663f, 6.5293f, 4.9598f, 7.3394f, 3.8533f, 8.6287f, 3.1996f, 10.0f, 3.2f};
const float holo_park_c1[] = {10.0f, 9.4f, 10.0f, 17.8f, 10.0f, 12.6f, 8.0f, 11.1f, 10.0f, 11.6f, 12.0f, 10.1f};
const IconShape holo_park_shapes[] = {
    {IconPaint::Accent, 0.32f, IconPaint::Current, 1.6f, "MCCCCLCCCCZ", holo_park_c0, 52},
    {IconPaint::None, 1.0f, IconPaint::Current, 1.6f, "MLMLML", holo_park_c1, 12},
};
const IconDrawing holo_park = {20.0f, true, holo_park_shapes, 2, nullptr};

const float holo_avenue_c0[] = {6.5f, 17.0f, 9.0f, 3.0f, 13.5f, 17.0f, 11.0f, 3.0f};
const float holo_avenue_c1[] = {10.0f, 5.2f, 10.0f, 6.8f, 10.0f, 9.2f, 10.0f, 10.8f, 10.0f, 13.2f, 10.0f, 15.0f};
const IconShape holo_avenue_shapes[] = {
    {IconPaint::None, 1.0f, IconPaint::Current, 1.6f, "MLML", holo_avenue_c0, 8},
    {IconPaint::None, 1.0f, IconPaint::Accent, 1.8f, "MLMLML", holo_avenue_c1, 12},
};
const IconDrawing holo_avenue = {20.0f, true, holo_avenue_shapes, 2, nullptr};

const float holo_street_c0[] = {10.0f, 18.0f, 10.0f, 9.5f};
const float holo_street_c1[] = {4.0f, 3.8f, 13.2f, 3.8f, 15.8f, 6.0f, 13.2f, 8.2f, 4.0f, 8.2f};
const float holo_street_c2[] = {7.0f, 18.0f, 13.0f, 18.0f};
const IconShape holo_street_shapes[] = {
    {IconPaint::None, 1.0f, IconPaint::Current, 1.6f, "ML", holo_street_c0, 4},
    {IconPaint::Accent, 0.32f, IconPaint::Current, 1.6f, "MLLLLZ", holo_street_c1, 10},
    {IconPaint::None, 1.0f, IconPaint::Current, 1.6f, "ML", holo_street_c2, 4},
};
const IconDrawing holo_street = {20.0f, true, holo_street_shapes, 3, nullptr};

const float holo_district_c0[] = {10.0f, 18.0f, 10.0f, 18.0f, 15.6f, 13.0f, 15.6f, 8.7f, 15.6f, 5.6072f, 13.0928f, 3.1f, 10.0f, 3.1f, 6.9072f, 3.1f, 4.4f, 5.6072f, 4.4f, 8.7f, 4.4f, 13.0f, 10.0f, 18.0f, 10.0f, 18.0f};
const float holo_district_c1[] = {12.2f, 8.7f, 12.2f, 9.915f, 11.215f, 10.9f, 10.0f, 10.9f, 8.785f, 10.9f, 7.8f, 9.915f, 7.8f, 8.7f, 7.8f, 7.485f, 8.785f, 6.5f, 10.0f, 6.5f, 11.215f, 6.5f, 12.2f, 7.485f, 12.2f, 8.7f};
const IconShape holo_district_shapes[] = {
    {IconPaint::None, 1.0f, IconPaint::Current, 1.6f, "MCCCCZ", holo_district_c0, 26},
    {IconPaint::Accent, 1.0f, IconPaint::None, 1.6f, "MCCCCZ", holo_district_c1, 26},
};
const IconDrawing holo_district = {20.0f, true, holo_district_shapes, 2, nullptr};

const float holo_water_c0[] = {2.8f, 8.6f, 4.6f, 7.0f, 6.4f, 10.2f, 8.2f, 8.6f, 10.0f, 7.0f, 11.8f, 10.2f, 13.6f, 8.6f, 15.4f, 7.0f, 16.2f, 9.6f, 17.2f, 9.0f, 2.8f, 13.0f, 4.6f, 11.4f, 6.4f, 14.6f, 8.2f, 13.0f, 10.0f, 11.4f, 11.8f, 14.6f, 13.6f, 13.0f, 15.4f, 11.4f, 16.2f, 14.0f, 17.2f, 13.4f};
const float holo_water_c1[] = {17.2f, 4.4f, 17.2f, 5.2837f, 16.4837f, 6.0f, 15.6f, 6.0f, 14.7163f, 6.0f, 14.0f, 5.2837f, 14.0f, 4.4f, 14.0f, 3.5163f, 14.7163f, 2.8f, 15.6f, 2.8f, 16.4837f, 2.8f, 17.2f, 3.5163f, 17.2f, 4.4f};
const IconShape holo_water_shapes[] = {
    {IconPaint::None, 1.0f, IconPaint::Current, 1.6f, "MCCCMCCC", holo_water_c0, 40},
    {IconPaint::Accent, 1.0f, IconPaint::None, 1.6f, "MCCCCZ", holo_water_c1, 26},
};
const IconDrawing holo_water = {20.0f, true, holo_water_shapes, 2, nullptr};

const IconDrawing poi_subway = {16.0f, false, nullptr, 0, "M"};

const float poi_cafe_c0[] = {3.0f, 5.0f, 11.0f, 5.0f, 11.0f, 9.0f, 11.0f, 10.6569f, 9.6569f, 12.0f, 8.0f, 12.0f, 6.0f, 12.0f, 4.3431f, 12.0f, 3.0f, 10.6569f, 3.0f, 9.0f, 11.0f, 6.0f, 12.5f, 6.0f, 13.3284f, 6.0f, 14.0f, 6.6716f, 14.0f, 7.5f, 14.0f, 8.3284f, 13.3284f, 9.0f, 12.5f, 9.0f, 11.0f, 9.0f};
const IconShape poi_cafe_shapes[] = {
    {IconPaint::None, 1.0f, IconPaint::White, 1.6f, "MLLCLCZMLCCL", poi_cafe_c0, 38},
};
const IconDrawing poi_cafe = {16.0f, false, poi_cafe_shapes, 1, nullptr};

const float poi_store_c0[] = {3.5f, 5.5f, 12.5f, 5.5f, 11.7f, 13.5f, 4.3f, 13.5f, 6.0f, 5.5f, 6.0f, 4.0f, 6.0f, 2.8954f, 6.8954f, 2.0f, 8.0f, 2.0f, 9.1046f, 2.0f, 10.0f, 2.8954f, 10.0f, 4.0f, 10.0f, 5.5f};
const IconShape poi_store_shapes[] = {
    {IconPaint::None, 1.0f, IconPaint::White, 1.6f, "MLLLZMLCCL", poi_store_c0, 26},
};
const IconDrawing poi_store = {16.0f, false, poi_store_shapes, 1, nullptr};

const float poi_music_c0[] = {6.0f, 12.2f, 6.0f, 3.8f, 12.5f, 2.2f, 12.5f, 10.6f};
const float poi_music_c1[] = {6.4f, 12.3f, 6.4f, 13.2941f, 5.5941f, 14.1f, 4.6f, 14.1f, 3.6059f, 14.1f, 2.8f, 13.2941f, 2.8f, 12.3f, 2.8f, 11.3059f, 3.6059f, 10.5f, 4.6f, 10.5f, 5.5941f, 10.5f, 6.4f, 11.3059f, 6.4f, 12.3f};
const float poi_music_c2[] = {12.9f, 10.7f, 12.9f, 11.6941f, 12.0941f, 12.5f, 11.1f, 12.5f, 10.1059f, 12.5f, 9.3f, 11.6941f, 9.3f, 10.7f, 9.3f, 9.7059f, 10.1059f, 8.9f, 11.1f, 8.9f, 12.0941f, 8.9f, 12.9f, 9.7059f, 12.9f, 10.7f};
const IconShape poi_music_shapes[] = {
    {IconPaint::None, 1.0f, IconPaint::White, 1.6f, "MLLL", poi_music_c0, 8},
    {IconPaint::White, 1.0f, IconPaint::None, 1.0f, "MCCCCZ", poi_music_c1, 26},
    {IconPaint::White, 1.0f, IconPaint::None, 1.0f, "MCCCCZ", poi_music_c2, 26},
};
const IconDrawing poi_music = {16.0f, false, poi_music_shapes, 3, nullptr};

const float poi_school_c0[] = {8.0f, 2.5f, 2.0f, 5.5f, 8.0f, 8.5f, 14.0f, 5.5f, 4.5f, 7.0f, 4.5f, 10.5f, 5.5f, 11.5f, 6.7f, 12.0f, 8.0f, 12.0f, 9.3f, 12.0f, 10.5f, 11.5f, 11.5f, 10.5f, 11.5f, 7.0f};
const IconShape poi_school_shapes[] = {
    {IconPaint::None, 1.0f, IconPaint::White, 1.5f, "MLLLZMLCCL", poi_school_c0, 26},
};
const IconDrawing poi_school = {16.0f, false, poi_school_shapes, 1, nullptr};

const float poi_book_c0[] = {3.0f, 3.5f, 7.0f, 3.5f, 7.4f, 3.5f, 7.8f, 3.7f, 8.0f, 4.0f, 8.2f, 3.7f, 8.6f, 3.5f, 9.0f, 3.5f, 13.0f, 3.5f, 13.0f, 12.5f, 9.0f, 12.5f, 8.6f, 12.5f, 8.2f, 12.7f, 8.0f, 13.0f, 7.8f, 12.7f, 7.4f, 12.5f, 7.0f, 12.5f, 3.0f, 12.5f, 8.0f, 4.0f, 8.0f, 13.0f};
const IconShape poi_book_shapes[] = {
    {IconPaint::None, 1.0f, IconPaint::White, 1.4f, "MLCCLLLCCLZML", poi_book_c0, 40},
};
const IconDrawing poi_book = {16.0f, false, poi_book_shapes, 1, nullptr};

const float poi_plaza_c0[] = {8.0f, 2.0f, 9.8f, 6.0f, 14.0f, 6.4f, 10.8f, 9.2f, 11.8f, 13.4f, 8.0f, 11.2f, 4.2f, 13.4f, 5.2f, 9.2f, 2.0f, 6.4f, 6.2f, 6.0f};
const IconShape poi_plaza_shapes[] = {
    {IconPaint::White, 1.0f, IconPaint::None, 1.0f, "MLLLLLLLLLZ", poi_plaza_c0, 20},
};
const IconDrawing poi_plaza = {16.0f, false, poi_plaza_shapes, 1, nullptr};

const float poi_park_c0[] = {8.0f, 2.5f, 4.0f, 8.0f, 6.5f, 8.0f, 4.0f, 11.5f, 12.0f, 11.5f, 9.5f, 8.0f, 12.0f, 8.0f, 8.0f, 11.5f, 8.0f, 14.0f};
const IconShape poi_park_shapes[] = {
    {IconPaint::White, 1.0f, IconPaint::White, 0.6f, "MLLLLLLZML", poi_park_c0, 18},
};
const IconDrawing poi_park = {16.0f, false, poi_park_shapes, 1, nullptr};

}  // namespace

const IconDrawing& holoIcon(LabelIcon icon) {
  switch (icon) {
    case LabelIcon::Subway:
      return holo_subway;
    case LabelIcon::Cafe:
      return holo_cafe;
    case LabelIcon::Store:
      return holo_store;
    case LabelIcon::Music:
      return holo_music;
    case LabelIcon::School:
      return holo_school;
    case LabelIcon::Book:
      return holo_book;
    case LabelIcon::Plaza:
      return holo_plaza;
    case LabelIcon::Park:
      return holo_park;
    case LabelIcon::Avenue:
      return holo_avenue;
    case LabelIcon::Street:
      return holo_street;
    case LabelIcon::District:
      return holo_district;
    case LabelIcon::Water:
      return holo_water;
  }
  return holo_subway;
}

const IconDrawing* poiGlyph(LabelIcon icon) {
  switch (icon) {
    case LabelIcon::Subway:
      return &poi_subway;
    case LabelIcon::Cafe:
      return &poi_cafe;
    case LabelIcon::Store:
      return &poi_store;
    case LabelIcon::Music:
      return &poi_music;
    case LabelIcon::School:
      return &poi_school;
    case LabelIcon::Book:
      return &poi_book;
    case LabelIcon::Plaza:
      return &poi_plaza;
    case LabelIcon::Park:
      return &poi_park;
    default:
      return nullptr;
  }
}

std::uint32_t iconColor(LabelIcon icon) {
  switch (icon) {
    case LabelIcon::Subway:
      return 0x2E9E6B;
    case LabelIcon::Cafe:
      return 0x9B6B43;
    case LabelIcon::Store:
      return 0xE0823A;
    case LabelIcon::Music:
      return 0x7B5CD6;
    case LabelIcon::School:
      return 0x4A7BD1;
    case LabelIcon::Book:
      return 0x3F8F8A;
    case LabelIcon::Plaza:
      return 0x2F5BEA;
    case LabelIcon::Park:
      return 0x4E9B55;
    case LabelIcon::Avenue:
      return 0xE3A23B;
    case LabelIcon::Street:
      return 0x3E7BFA;
    case LabelIcon::District:
      return 0x7B61FF;
    case LabelIcon::Water:
      return 0x2E9BD6;
  }
  return 0;
}

std::string_view poiSubtitle(PoiCategory category) {
  switch (category) {
    case PoiCategory::Subway:
      return "지하철역 · STATION";
    case PoiCategory::Cafe:
      return "카페 · CAFE";
    case PoiCategory::Store:
      return "편의점 · STORE";
    case PoiCategory::Music:
      return "음반 · RECORDS";
    case PoiCategory::School:
      return "학교 · SCHOOL";
    case PoiCategory::Book:
      return "서점 · BOOKS";
    case PoiCategory::Plaza:
      return "광장 · PLAZA";
    case PoiCategory::Park:
      return "공원 · PARK";
  }
  return {};
}

std::string_view kindSubtitle(LabelIcon icon) {
  switch (icon) {
    case LabelIcon::Avenue:
      return "대로 · AVENUE";
    case LabelIcon::Street:
      return "도로 · STREET";
    case LabelIcon::District:
      return "동 · DISTRICT";
    case LabelIcon::Water:
      return "하천 · RIVER";
    default:
      return {};
  }
}

}  // namespace maprama
