/**
 * `@maprama/protocol`: the shared contract between Maprama hosts (React Native,
 * tools, services) and render engines (web, native).
 *
 * - {@link createProjection}: `{ lng, lat }` ⇄ world units.
 * - {@link WorldData}: vector map data schema.
 * - {@link ThemeSpec} / {@link resolveTheme}: themes and built-in presets.
 * - {@link EngineCommand} / {@link EngineEvent}: the message protocol and codec.
 *
 * @packageDocumentation
 */

export type { ValidationResult } from './internal/validate.js';

export {
  DEFAULT_UNIT_METERS,
  EARTH_RADIUS_METERS,
  METERS_PER_DEGREE_LAT,
  METERS_PER_DEGREE_LNG,
  createProjection,
  haversineMeters,
} from './geo.js';
export type { LngLat, LngLatBounds, Projection, ProjectionOptions, WorldPoint } from './geo.js';

export {
  BUILDING_KINDS,
  POI_CATEGORIES,
  PROCEDURAL_LAYOUTS,
  ROAD_CLASSES,
  WORLD_DATA_VERSION,
  validateWorldData,
  validateWorldSource,
} from './world.js';
export type {
  BuildingFootprint,
  BuildingKind,
  District,
  Park,
  Poi,
  PoiCategory,
  Polygon,
  ProceduralLayout,
  Road,
  RoadClass,
  Station,
  TileWorldSource,
  Vec2,
  WorldBounds,
  WorldData,
  WorldSource,
} from './world.js';

export {
  MTIL_BUFFER,
  MTIL_EXTENT,
  MTIL_FORMAT,
  MTIL_LAYERS,
  MTIL_LAYER_NAMES,
  MTIL_LAYER_OWNERSHIP,
  MTIL_MAGIC,
  MTIL_VERSION,
  TileDecodeError,
  decodeTile,
  resolveTileAttribution,
  validateTileArchiveMetadata,
} from './tile.js';
export type {
  MtilLayerName,
  MtilTile,
  TileArchiveMetadata,
  TileBuilding,
  TileDistrict,
  TileLayers,
  TilePark,
  TilePoi,
  TileRoad,
  TileStation,
  TileVec2,
  TileWater,
} from './tile.js';

export {
  BASE_THEME_DEFAULTS,
  FACADE_SETS,
  LANDMARK_GLASS_STYLES,
  MASSING_MODES,
  PRESET_NAMES,
  SHADING_MODELS,
  TIMES_OF_DAY,
  ZOOM_OUT_BEHAVIORS,
  resolveTheme,
  validateThemePreset,
  validateThemeSpec,
} from './theme.js';
export type {
  FacadeSet,
  LandmarkColors,
  LandmarkGlass,
  Massing,
  PresetDefaults,
  PresetName,
  ResolvedTheme,
  ShadingModel,
  ThemePreset,
  ThemeSpec,
  TimeOfDay,
  TimeOfDayPreset,
  ZoomOutBehavior,
} from './theme.js';

export { CINE, INK, PRESETS, PRESET_DEFAULTS, TIMES, minimal, modern, realistic, soft, toy, urban } from './presets/index.js';

export { HOLO_ICON_TILES, LABEL_CONTENT_MODES, LABEL_ICONS, LABEL_KINDS, LABEL_STYLES } from './labels.js';
export type {
  HoloIconTile,
  LabelContent,
  LabelContentMode,
  LabelIcon,
  LabelInfo,
  LabelKind,
  LabelStyle,
  LabelsSpec,
} from './labels.js';

export {
  INFO_BADGE_TONES,
  INFO_CARD_ANCHORS,
  INFO_CARD_GROUND_HEIGHT_METERS,
  INFO_CARD_ROOF_HEIGHT_METERS,
  INFO_ROW_ICONS,
} from './info-card.js';
export type {
  InfoBadgeTone,
  InfoCardAction,
  InfoCardAnchor,
  InfoCardBadge,
  InfoCardContent,
  InfoCardRating,
  InfoCardRow,
  InfoCardSpec,
  InfoRowIcon,
} from './info-card.js';

export {
  ANIMATION_NAMES,
  BUILDING_DECORATIONS,
  CAMERA_FOV_DEG,
  DROP_TYPES,
  DEFAULT_SNAP_TO_BUILDING_METERS,
  LOCATION_SOURCE_KINDS,
  MARKER_ANCHORS,
  MARKER_ANCHOR_HEIGHTS,
  MARKER_SHAPES,
  RARITIES,
  ROOF_SHAPES,
  TRAVEL_MODES,
  visibleSpanMeters,
} from './entities.js';
export type {
  AnimationName,
  BuildingDecoration,
  BuildingStyle,
  CameraSpec,
  CharacterSpec,
  ContentInset,
  DropSpec,
  DropType,
  GeofenceSpec,
  JsonValue,
  LocationFix,
  LocationSourceKind,
  MapUiSpec,
  MarkerAnchor,
  MarkerAnchorHeight,
  MarkerIcon,
  MarkerImage,
  MarkerShape,
  MarkerSnapToBuilding,
  MarkerSpec,
  ModelSource,
  Rarity,
  RoofShape,
  TravelMode,
} from './entities.js';

export {
  CAMERA_IDLE_DELAY_MS,
  CAMERA_IDLE_HORIZON_FACTOR,
  CAMERA_IDLE_REASONS,
  ENGINE_COMMAND_TYPES,
  ENGINE_EVENT_TYPES,
  ENGINE_KINDS,
  FIT_BOUNDS_ORIENTATIONS,
  PROTOCOL_VERSION,
  REQUEST_METHODS,
  SUBSCRIPTION_TOPICS,
  decodeCommand,
  decodeEvent,
  encodeCommand,
  encodeEvent,
  validateEngineCommand,
  validateEngineEvent,
} from './messages.js';
export type {
  BuildingPressEvent,
  CameraChangeEvent,
  CameraIdleEvent,
  CameraIdleReason,
  CameraState,
  CancelTravelCommand,
  CharacterPositionEvent,
  CommandEnvelope,
  DecodeResult,
  DropCollectEvent,
  EngineCommand,
  EngineCommandType,
  EngineErrorCode,
  EngineEvent,
  EngineEventType,
  EngineInfo,
  EngineKind,
  Envelope,
  ErrorEvent,
  FitBoundsOrientation,
  FitBoundsPadding,
  FitBoundsParams,
  FitBoundsResult,
  FocusOnParams,
  FocusOnResult,
  EventEnvelope,
  GeofenceEnterEvent,
  GeofenceExitEvent,
  InfoCardDismissEvent,
  InfoCardPressEvent,
  InitCommand,
  LabelsIndexEvent,
  MapPressEvent,
  MarkerPressEvent,
  MessageKind,
  OverlayAnchor,
  OverlayPosition,
  OverlayPositionsEvent,
  ProtocolError,
  PushLocationCommand,
  ReadyEvent,
  RemoveCharactersCommand,
  RemoveDropLayerCommand,
  RemoveInfoCardCommand,
  RemoveMarkerLayerCommand,
  RequestCommand,
  RequestCommandOf,
  RequestMethod,
  RequestParamsMap,
  RequestResultMap,
  ResponseErrorEvent,
  ResponseEvent,
  ResponseOkEvent,
  RouteLeg,
  RouteResult,
  ScreenPoint,
  SetBuildingStyleCommand,
  SetCameraCommand,
  SetDropLayerCommand,
  SetGeofencesCommand,
  SetInfoCardCommand,
  SetLabelContentCommand,
  SetLabelsCommand,
  SetLocationSourceCommand,
  SetMarkerLayerCommand,
  SetOverlayAnchorsCommand,
  SetThemeCommand,
  SetUiCommand,
  SetViewCommand,
  SnapToBuildingResult,
  SnapToRoadResult,
  SubscribeCommand,
  SubscriptionTopic,
  TravelArriveEvent,
  TravelCancelEvent,
  TravelCommand,
  TravelLeg,
  TravelProgressEvent,
  TravelStartEvent,
  UnsubscribeCommand,
  UpsertCharactersCommand,
  ViewChangeEvent,
} from './messages.js';

export { DEFAULT_VIEW_MODE, VIEW_MODES, VIEW_TRANSITION_MS } from './view.js';
export type { ViewMode } from './view.js';
